# -*- coding: utf-8 -*-
# @Author: Rafael Direito
# @Date:   2024-06-14 13:12:30
# @Last Modified by:   Rafael Direito
# @Last Modified time: 2024-06-14 13:38:38
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: es-obu-dt-5gasp
  name: es-obu-dt-5gasp-service
spec:
  type: NodePort
  ports:
    - name: "mqtt"
      port: 1883
      targetPort: 1883
      nodePort: 30001
      protocol: TCP
    - name: "grafana"
      port: 9000
      targetPort: 9000
      nodePort: 30002
      protocol: TCP
  selector:
    io.kompose.service: es-obu-dt-5gasp

