{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
  - http:
      paths:
      - path: "/lamda-ui(.*)"
        pathType: Prefix
        backend:
          service:
            name: angular-service
            port:
              number: 9000
{{- end }}


# app.privacyanalyzer.lamdanetworks.io