apiVersion: v1
kind: Service
metadata:
  name: flaskweb-service
spec:
  selector:
    app: flaskweb
  type: {{ if .Values.ingress.enabled }} ClusterIP {{ else }} NodePort {{ end }}
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
    {{ if not .Values.ingress.enabled }}
    nodePort: 30003
    {{ end }}
