{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniapi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
  - http:
      paths:
      - path: "/lamda-miniapi/(.*)"
        pathType: Prefix
        backend:
          service:
            name: miniapi-service
            port:
              number: 13001
{{- end }}

# miniapi.privacyanalyzer.lamdanetworks.io