apiVersion: v1
kind: Service
metadata:
  name: miniapi-service
spec:
  selector:
    app: networkapp-miniapi
  type: {{ if .Values.ingress.enabled }} ClusterIP {{ else }} NodePort {{ end }}
  ports:
  - protocol: "TCP"
    port: 13001
    targetPort: 13001
    {{ if not .Values.ingress.enabled }}
    nodePort: 30001
    {{ end}}

